### ISSUE TITLE
SocketManager is not defined

### ISSUE THREAD

**Issue by stefanoScalzo** [triniwiz/nativescript-socketio#102]
### Make sure to check the demo app(s) for sample usage 
Demo app not up to date
### Make sure to check the existing issues in this repository 
None
### If the demo apps cannot help and there is no issue for your problem, tell us about it
Please, ensure your title is less than 63 characters long and starts with a capital
letter.
Trying to create a basic socket in NS angular and throwing "SocketManager is not defined" exception.

### Which platform(s) does your issue occur on?
- IOS
Emulator: iphone11

### Please, provide the following version numbers that your issue occurs with:

- CLI: (run `tns --version` to fetch it) 7.0.11
- Cross-platform modules: (check the 'version' attribute in the
`node_modules/tns-core-modules/package.json` file in your project)
- Runtime(s): (look for the `"tns-android"` and `"tns-ios"` properties in the `package.json` file of your project)
- Plugin(s): (look for the version numbers in the `package.json` file of your
project and paste your dependencies and devDependencies here)
4.0.1
### Please, tell us how to recreate the issue in as much detail as possible. 
do ns clean
npm i 
try and instantiate SocketIO instance

Wild guess: It seems like the SocketManager in the index.ios.js needs an import that isn't being supplied?
Thanks

### Is there any code involved? 
component: 
```
import { SocketIOModule } from "@triniwiz/nativescript-socketio/angular";
let socketIO = new SocketIO(http://localhost:3000/);
```
module: 
```
import { SocketIOModule } from "@triniwiz/nativescript-socketio/angular";
SocketIOModule.forRoot(http://localhost:3000/)
```

**Comment by stefanoScalzo** [comment]
@triniwiz is this a bug or am I not implementing the code right?

**Comment by M-Massey** [comment]
@triniwiz  I can also reproduce this issue.
