### ISSUE TITLE
this.socket.connect is not a function

### ISSUE THREAD

**Issue by kambl4** [triniwiz/nativescript-socketio#103]
> ns version 8.0.2
>"nativescript-vue": "~2.9.0",
>"@triniwiz/nativescript-socketio": "^4.0.1"

In my app.js

```
import { SocketIO } from '@triniwiz/nativescript-socketio';
const socketIO = new SocketIO(SOCKET_URL, {});

new Vue({
  render: (h) => h('frame', [h(Login)]),
  mounted () {
    socketIO.connect();
  }
}).$start()
```

After I run `ns run ios` I'm getting this error

```
(CoreFoundation) *** Terminating app due to uncaught exception 'NativeScript encountered a fatal error: 
Uncaught TypeError: this.socket.connect is not a function
at
connect(file: app/webpack:/hivlife-app/node_modules/@triniwiz/nativescript-socketio/index.ios.js:154:0)
at mounted(file: app/webpack:/hivlife-app/app/app.js:45:0)
```

How to fix?

**Comment by triniwiz** [comment]
I need to publish a fix for that the pod needs to point to the previous branch

**Comment by triniwiz** [comment]
Give `@triniwiz/nativescript-socketio@4.0.2` a try an lmk or you can update to `5.0.0` to use the latest socket.io servers

**Comment by kambl4** [comment]
`@triniwiz/nativescript-socketio@4.0.2` works! Thank you 😃
