### ISSUE TITLE
iOS Demo app issues

### ISSUE THREAD

**Issue by jwhits** [triniwiz/nativescript-socketio#11]
The android demo app seems to work fine. I am having a couple of issues with the iOS demo app. It starts and connects to the server but there is a few errors and it doesn't send messages or get the list of previously sent messages to display on screen.

This error is appears just after the build is completed. Followed by a dump.
`assertion failed: 15F34 13E230: libxpc.dylib + 71506 [6F98A9DA-B46E-3A2B-88D4-92F1EC77477F]: 0x7d`

Here is the iOS demo app connection to the server.

```
Joined Namespace: /
User Connected
```

Here is the login followed by another error.

```
Login:  (
            {
            userList =         (
                            {
                    username = Osei;
                }
            );
        }
    )
: CONSOLE LOG file:///app/tns_modules/nativescript-socketio/socketio.js:28:24: Event: getMessages
 --- last message repeated 3 times ---
: (Error) MC: MobileContainerManager gave us a path we weren't expecting; file a radar against them
    Expected: /private/var/containers/Shared/SystemGroup/systemgroup.com.apple.configurationprofiles
    Actual: /Users/username/Library/Developer/CoreSimulator/Devices/4234F2B9-8FF7-4645-AB78-AA01434D9FB6/data/Containers/Shared/SystemGroup/systemgroup.com.apple.configurationprofiles
    Overriding MCM with the one true path
```

When trying to send a message the server throws this error.

```
Missing error handler on 'socket'.
TypeError: cb is not a function
    at Socket.<anonymous> (/Users/username/Documents/Joel/Code/apps/Nativescript/nativescript-socketio/demo/demo-server/app.js:29:9)
```

Any ideas what is going on?

**Comment by triniwiz** [comment]
@db3dev anything ?

**Comment by db3coder** [comment]
The original demo app was created with Android in mind. Running it on IOS is not the same experience. The functionality of the plugin works which is demonstrated with console.log. If you check the server side you'll see it is receiving and sending messages. If you login simultaneously with an Android app it will populate them.

I'm not familiar with nativescript apps without being built with angular so I haven't attempted to adjust the UI.
