### ISSUE TITLE
Image and/or video stream ?

### ISSUE THREAD

**Issue by developper89** [triniwiz/nativescript-socketio#16]
Is there a way to send images or video throug the socket ? basically as a stream ?
i figured it out how to handle base64 images but it's quite heavy for big ones.

**Comment by triniwiz** [comment]
I came across this for android https://github.com/socketio/socket.io-client-java/blob/master/src/test/java/io/socket/client/ConnectionTest.java#L866-L919 and for ios https://github.com/socketio/socket.io-client-swift/issues/389#issuecomment-224575990

**Comment by developper89** [comment]
thanks
