### ISSUE TITLE
Failed to find module: "nativescript-socketio"

### ISSUE THREAD

**Issue by cdiaz** [triniwiz/nativescript-socketio#19]
Failed to find module: "nativescript-socketio", relative to :/app/tns_modules/ .. 

I try 
`tns plugin add nativescript-socketio  
`and
`npm install nativescript-socketio
`
tns version:  2.2.1
nodejs v5.7.0
Ubuntu 16.4

**Comment by triniwiz** [comment]
can you share a screenshot of `node_modules/nativescript-socketio`

**Comment by cdiaz** [comment]
Hi @triniwiz
![alt text](http://quantux.co/node_modules.png)

**Comment by triniwiz** [comment]
Fixed with https://github.com/triniwiz/nativescript-socketio/commit/765a6f5ddea3b278ac0bec578cdd1ce49525f9c7

**Comment by triniwiz** [comment]
you will need to update your module to `2.2.0`
