### ISSUE TITLE
trouble with Xcode upgrade 8.0

### ISSUE THREAD

**Issue by developper89** [triniwiz/nativescript-socketio#21]
i had to update the podfile to make it work with Xcode 8.0
`pod 'Socket.IO-Client-Swift', '~> 8.0.0'`
could you update the podfile ?

**Comment by triniwiz** [comment]
Done https://github.com/triniwiz/nativescript-socketio/commit/e13cdfcd485fe83e375893dd7a3fcd655be54aef
