### ISSUE TITLE
Use Swift 2.3 branch for pod file

### ISSUE THREAD

**Issue by roblav96** [triniwiz/nativescript-socketio#23]
I've been experimenting with attempts to get this to build on ios10 and xcode8. This is the pod spec you want to use:

``` ruby
pod 'Socket.IO-Client-Swift', :git => 'https://github.com/socketio/socket.io-client-swift.git', :branch => 'swift2.3'
```

When asked to `convert Swift code` in xcode choose `2.3`.

Based off this research:
https://github.com/socketio/socket.io-client-swift/issues/492

I get this error when trying to install the way it is currently:

```
[!] Unable to satisfy the following requirements:

- `Socket.IO-Client-Swift (~> 8.0.0)` required by `Podfile`

None of your spec sources contain a spec satisfying the dependency: `Socket.IO-Client-Swift (~> 8.0.0)`.

You have either:
 * out-of-date source repos which you can update with `pod repo update`.
 * mistyped the name or version.
 * not added the source repo that hosts the Podspec to your Podfile.

Note: as of CocoaPods 1.0, `pod repo update` does not happen on `pod install` by default.
```

**Comment by triniwiz** [comment]
Uses the the latest now https://github.com/triniwiz/nativescript-socketio/commit/826a01a2d13ee7d9cd61ff34dcf0ff9f854f77d2 (v13.x)
