### ISSUE TITLE
Unbind socketIo events : Off / removeListener

### ISSUE THREAD

**Issue by odubuc** [triniwiz/nativescript-socketio#25]
Is there any way to unbind an event?

from:
`socketIO.on(event, callback);`

to:
`socketIO.removeListener(event, callback);`
(like socketio)

or simply:
`socketIO.off(event,callback);`

**Comment by triniwiz** [comment]
atm no but i will add it

**Comment by roblav96** [comment]
@triniwiz @odubuc  this is my temp destroy if its something you're looking for

``` typescript
destroy() {
    if (SocketClass._socket) {
        SocketClass._socket.disconnect()
        if (application.ios) {
            SocketClass._socket.instance.removeAllHandlers()
        } else if (application.android) {
            SocketClass._socket.instance.close()
        }
        SocketClass._socket = null
    }
}
```

lulz

**Comment by triniwiz** [comment]
@roblav96  there is a `.off()` just need to wire it up :smiley:  thanks anyhow

**Comment by FranciZ** [comment]
@triniwiz Is it possible to `off` a specific function like `socketIO.off(event,callbackRef);`?
