### ISSUE TITLE
Can't find variable: SocketIOClient

### ISSUE THREAD

**Issue by terreb** [triniwiz/nativescript-socketio#27]
I get this when run the demo app on iOS 9.3 simulator:
file:///app/tns_modules/nativescript-socketio/socketio.js:33:49: JS ERROR ReferenceError: Can't find variable: SocketIOClient

**Comment by terreb** [comment]
Also, when I run "tns build ios" it fails with:
"Command xcodebuild failed with exit code 65"
I have xCode 7.3.1
nativescript-socketio version is 2.2.7

**Comment by triniwiz** [comment]
Update and try again also you will need Xcode 8+

**Comment by terreb** [comment]
X)
