### ISSUE TITLE
Demo App not running on android

### ISSUE THREAD

**Issue by tviel** [triniwiz/nativescript-socketio#28]
# Hi,

due to problems with the plugin on ios (see #26), I decided to check, if I have the same issues on android to specify if it is more related to my sources or the native part.

So first I tried to run my app on an android emulator, which resulted in problems in the require of the plugin:

![image](https://cloud.githubusercontent.com/assets/1053681/19427386/07e5bcf4-9444-11e6-911c-233df6e2c755.png)

So I decided to give the demo app a try. Cloned the repo, started server as documented and switched to the app. Also here I followed the two steps from docs, which made a successfull built. But trying to run the demo resulted in:

![image](https://cloud.githubusercontent.com/assets/1053681/19427368/e9272082-9443-11e6-897d-407ed3eba80b.png)

I'm outta luck on my side.

**Comment by roblav96** [comment]
Remove `platforms` and `node_modules` folders then run:

```
npm install
tns install
tns prepare android
tns run android
```
