### ISSUE TITLE
IOS: TypeError: this.socket.emitWithAckWithItems

### ISSUE THREAD

**Issue by kvindascr** [triniwiz/nativescript-socketio#34]
When trying to call emit with a callback, it report back the error.

`IOS: TypeError: this.socket.emitWithAckWithItems`

After reviewing the POD code seems that the right name is 

`IOS: TypeError: this.socket.emitWithAckWith`

I corrected this on typing for ios on the plugin, but even after correction I started to get.

`TypeError: emit is not a function`

**Comment by triniwiz** [comment]
Fixed
