### ISSUE TITLE
how to connect to https

### ISSUE THREAD

**Issue by wiliarko** [triniwiz/nativescript-socketio#35]
how to connect to https example : https:demo.com:5808

how to connect to https, I've tried if http work but https failed

**Comment by roblav96** [comment]
@wiliarko 
```typescript
let Socket = new SocketIO('https://wegossipapp.com', {
		path: '/socket',
		forceNew: false,
	})
```

**Comment by wiliarko** [comment]
i use this

var options = {
        forceNew: false
    };
 let   socket = SocketIO.connect('https://try.worksaurus.com:58082', options);

I've tried, and the results can not connet

**Comment by roblav96** [comment]
That's a server config problem =/

My server opts looks like:
```typescript
const io: SocketIO.Server = SocketIO(9876, {
	path: '/socket',
	serveClient: false,
	transports: ['websocket'],
})
```
