### ISSUE TITLE
Failed to find module "nativescript-socketio"

### ISSUE THREAD

**Issue by Luban-Yuumi** [triniwiz/nativescript-socketio#39]
npm install nativescript-socketIO Error

**Comment by triniwiz** [comment]
you are trying to install the incorrect package `npm install nativescript-socketIO Error` =>` npm install nativescript-socketio`

**Comment by Luban-Yuumi** [comment]
Can u update your plugin so that it can run on nativescript 3.0 ,I will very appreciate it .thank you.

**Comment by triniwiz** [comment]
The plugin is compatible with 3.0

**Comment by Luban-Yuumi** [comment]
thank you ~
