### ISSUE TITLE
iOS support

### ISSUE THREAD

**Issue by triniwiz** [triniwiz/nativescript-socketio#4]
Using official SDK:
 https://github.com/socketio/socket.io-client-swift

**Comment by triniwiz** [comment]
Added https://github.com/triniwiz/nativescript-socketio/commit/399fad517c624c728697a50eb62d7d12e78e6403

**Comment by jwhits** [comment]
Just confirming iOS now support is now added?

**Comment by triniwiz** [comment]
@jwhits yes :smile:

**Comment by jwhits** [comment]
Awesome! nice work @triniwiz

**Comment by triniwiz** [comment]
@jwhits thanks to @db3dev :beers:
