### ISSUE TITLE
iOS: Socket.IO-Client-Swift error on build

### ISSUE THREAD

**Issue by budilovskiy** [triniwiz/nativescript-socketio#41]
Hi. When I'm trying to run app with **nativescript-socketio** plugin, i get an error during building process:
```
.../platforms/ios/Pods/Socket.IO-Client-Swift/Source/SocketIOClientConfiguration.swift:28:62: error: 'Generator' has been renamed to 'Iterator'
    public typealias Generator = Array<SocketIOClientOption>.Generator
                                                             ^~~~~~~~~
                                                             Iterator
Swift.Collection:3:22: note: 'Generator' has been explicitly marked unavailable here
    public typealias Generator = Self.Iterator
                     ^
```

After changing `pod 'Socket.IO-Client-Swift', ‘8.0.2’` to `pod 'Socket.IO-Client-Swift', ‘8.3.0’` in Podfile application starts normally.
Could you update the version of **Socket.IO-Client-Swift**?

**Comment by roblav96** [comment]
@budilovskiy ill try this out and publish if it works. Thanks for the pointer.

**Comment by triniwiz** [comment]
fixed in the new release
