### ISSUE TITLE
problems on iOS

### ISSUE THREAD

**Issue by budilovskiy** [triniwiz/nativescript-socketio#44]
There is a problem with sending / receiving messages on iOS.
For example this piece of code:
on client:
```
this.socket.emit("string", "SOME STRING");
```
on server:
```
socket.on('string', (value: string) => {
    console.log("Received string from client: " + value);
}
```
writes to console this: `Received string from client:  undefined`

The same problem is observed on sending / receiving JSON objects and on both direction: from client to server and vise versa

Full example of this problem is available at [https://github.com/AlexanderRay/socketIoWithIosIssue](https://github.com/AlexanderRay/socketIoWithIosIssue)

**Comment by okdevwww** [comment]
@budilovskiy 
so did you solve this problem?
I have got same problem.

**Comment by juanitozambada** [comment]
@budilovskiy
@triniwiz 
so did you solve this problem?
I have got same problem.

**Comment by budilovskiy** [comment]
@okdevwww 
@juanitozambada 
No, unfortunately, I did not solve the problem
