### ISSUE TITLE
on TNS 3.0.1 its breaking my app

### ISSUE THREAD

**Issue by devyaz** [triniwiz/nativescript-socketio#45]
i did a normal install 
 `tns plugin add nativescript-socketio`  that made my app build fail! then i did 
`tns plugin remove nativescript-socketio`  and did an npm install, but it still wont build my app now i tried a new project run it then added tns socketio and the new app failed to build!! removed it and the app run!
is it meant to run on nativescript 3.0.1??? pliz help i need socketio

**Comment by devyaz** [comment]
am running on  Android 6

**Comment by triniwiz** [comment]
It should be working now
