### ISSUE TITLE
Demo failed (Android)

### ISSUE THREAD

**Issue by tamnvt** [triniwiz/nativescript-socketio#5]
Hi triniwiz, 
I can not run the demo with cloned source code.
Steps:
- start demo server (succesfull)
- tns run android
  Error found:
  Found peer TypeScript 1.8.10
  app/login.ts(2,24): error TS2307: Cannot find module 'nativescript-socketio'.
  app/main-page.ts(5,24): error TS2307: Cannot find module 'nativescript-socketio'.

I also encounter this issue with my project using nativescript-socketio npm.
Please help me to resolve it. 
Many thanks

**Comment by tamnvt** [comment]
I worked around by this:
var SocketIO = require('nativescript-socketio').SocketIO; 
it works !
But in my class, I can define property type by:
private socketInstance: SocketIO 
Error from VSCode notification:
[ts]
Cannot find name 'SocketIO'

**Comment by db3coder** [comment]
npm run demo.android from root works for me

**Comment by triniwiz** [comment]
@tamnvt upgrade your plugin to version `2.0.0`

**Comment by jwhits** [comment]
I am also having this issue.  I have updated plugin version to `2.0.0` the app starts and gets to the login screen however when I press join nothing happens. I can't see any other errors apart from the one mentioned above.

The server logs
`Joined Namespace: /
User Connected
Joined Namespace: /chat`

**Comment by triniwiz** [comment]
@jwhits i need to update the demo and the docs :sweat_smile:

**Comment by jwhits** [comment]
Well that would explain it @triniwiz :)

**Comment by triniwiz** [comment]
Closing this since https://github.com/triniwiz/nativescript-socketio/commit/6b1e186a9a44ac5b806bf1f182fe739df50137c4 included a fix for typings so no more `Cannot find module 'nativescript-socketio'` also @jwhits the demo has been updated
