### ISSUE TITLE
Unicode problem

### ISSUE THREAD

**Issue by burawi** [triniwiz/nativescript-socketio#52]
The package seems to be not parsing data as unicode. Is there any way to emit and receive unicode ?

**Comment by triniwiz** [comment]
I’m going to guess this is iOS ?

**Comment by burawi** [comment]
No it's android...
When I emit arabic text, Eg: "ق" I get "B"
And when I emit this char 'é' the function is not getting called

**Comment by triniwiz** [comment]
Next release should fix this

**Comment by burawi** [comment]
thanks

**Comment by burawi** [comment]
I just found the solution. Upgrade `socket.io-client` to 1.0.0.
In `platforms/android/include.gradle`  change this:
```javascript
dependencies {
	compile('io.socket:socket.io-client:0.8.2') {
		exclude group: 'org.json', module: 'json'
	}
}
```
by this:
```javascript
dependencies {
	compile('io.socket:socket.io-client:1.0.0') {
		exclude group: 'org.json', module: 'json'
	}
}
```
