### ISSUE TITLE
Cannot find module 'nativescript-socketio/angular'

### ISSUE THREAD

**Issue by ramonjobsity** [triniwiz/nativescript-socketio#53]
Hi. I m trying to import the module 'nativescript-socketio/angular' after installed  tns plugin add nativescript-socketio. Regards

**Comment by ramonjobsity** [comment]
and i have this Cannot find module 'nativescript-socketio/angular'

**Comment by moayadnajd** [comment]
@ramonjobsity and @triniwiz i  think the angular folder is not exist on the npm

**Comment by moayadnajd** [comment]
i just clone the GitHub and put in my package.json and its working fine so the problem is why the angular folder not in the npm  

`  "nativescript-socketio": "file:nativescript-socketio",`

**Comment by FranciZ** [comment]
@triniwiz Could you please update the npm with the Angular version. As it is, the Angular example is not working. Would really appreciate it!

**Comment by triniwiz** [comment]
Updated
