### ISSUE TITLE
Error on iOS build after plugin added

### ISSUE THREAD

**Issue by geoff-riverkids** [triniwiz/nativescript-socketio#55]
Getting this error after trying to create my running project for iOS.

Installing pods...
Analyzing dependencies
[!] CocoaPods could not find compatible versions for pod "Socket.IO-Client-Swift":
  In Podfile:
    Socket.IO-Client-Swift (~> 10.3.1)

    Socket.IO-Client-Swift (~> 11.1.3)

    Socket.IO-Client-Swift (~> 11.2.1)

    Socket.IO-Client-Swift (~> 11.3.1)

    Socket.IO-Client-Swift (~> 9.0.1)

None of your spec sources contain a spec satisfying the dependencies: `Socket.IO-Client-Swift (~> 11.3.1), Socket.IO-Client-Swift (~> 11.2.1), Socket.IO-Client-Swift (~> 11.1.3), Socket.IO-Client-Swift (~> 10.3.1), Socket.IO-Client-Swift (~> 9.0.1)`.

You have either:
 * out-of-date source repos which you can update with `pod repo update` or with `pod install --repo-update`.
 * mistyped the name or version.
 * not added the source repo that hosts the Podspec to your Podfile.

Note: as of CocoaPods 1.0, `pod repo update` does not happen on `pod install` by default.
Unable to apply changes on device: F2A461E5-7335-4BB5-8659-5A16D9A2FC1B. Error is: Command pod failed with exit code 31 Error output: 

I added some random ones aside from 11.1.3 in the code repo to try to get something to work.

..
    "tns-android": {
      "version": "3.4.1"
    },
    "tns-ios": {
      "version": "3.4.1"
    }
  },
  "dependencies": {
    "nativescript-socketio": "^2.4.0",
    "nativescript-theme-core": "~1.0.4",
    "nativescript-ui-calendar": "^3.5.2",
    "nativescript-ui-chart": "^3.5.0",
    "nativescript-ui-dataform": "^3.5.2",
    "nativescript-ui-gauge": "^3.5.0",
    "nativescript-ui-listview": "^3.5.1",
    "tns-core-modules": "^3.4.1"
  },
  "devDependencies": {
    "babel-traverse": "6.4.5",
    "babel-types": "6.4.5",
    "babylon": "6.4.5",
    "css-loader": "~0.28.7",
    "lazy": "1.0.11",
    "nativescript-dev-typescript": "^0.6.0",
    "nativescript-worker-loader": "~0.8.1",
    "raw-loader": "~0.5.1",
    "resolve-url-loader": "~2.2.1",
    "typescript": "^2.7.2"
  }

TIA

**Comment by triniwiz** [comment]
Fixed in 3.x
