### ISSUE TITLE
r.removeListener is not a function

### ISSUE THREAD

**Issue by xeroxstar** [triniwiz/nativescript-socketio#58]
Hello, i am trying to remove a emit function with removeListener but i getting an error:

`System.err: TypeError: r.removeListener is not a function
System.err: File: "file:///data/data/org.nativescript.application/files/app/app.js, line: 1, column: 6442`

I tried to declare "off" function in socketio.t.ds file but still, it does not work.
Here is the basic code:

```
socketIO = new SocketIO(url, options);
socketIO.removeListener('hello');  //socketIO.off('hello')
socketIO .on('hello',function(data){
})
```

**Comment by triniwiz** [comment]
You can use the off now added https://github.com/triniwiz/nativescript-socketio/commit/34970539e755e3128406be87205b23043faef545
