### ISSUE TITLE
Cannot find namespace 'io'

### ISSUE THREAD

**Issue by BlackCat1606** [triniwiz/nativescript-socketio#59]
Hi , i was trying out the demo-ng and i've got this error while executing : tns run android .

node_modules/nativescript-socketio/socketio.android.d.ts(3,23): error TS2503: Cannot find namespace 'io'

can you help please

**Comment by BlackCat1606** [comment]
i just solved the issue by changing the type of the variable socket which was io.socket.client.Socket to any in the file socketio.android.d.ts which solved the problem for me .

**Comment by IdanDavidi** [comment]
I face this issue as well

**Comment by BlackCat1606** [comment]
@IdanDavidi  did you solve it ?

**Comment by IdanDavidi** [comment]
@BlackCat1606 Your suggestion works but this is not a solution, this is not reasonable to change the `socketio.android.d.ts` file under `node_modules`.

I suspect it has something to do with the typescript version. I am using 2.7.2, what is your version?

**Comment by BlackCat1606** [comment]
2.6.2 , it didn't seem reasonable also to me , i tried other typescript versions but still the same problem

**Comment by IdanDavidi** [comment]
@BlackCat1606 maybe you should reopen the issue

**Comment by BlackCat1606** [comment]
@IdanDavidi  , i will reopen it

**Comment by dalsscarlon** [comment]
I have the same issue.

**Comment by kefahB** [comment]
Hi,

if declared socketio: any (by @BlackCat1606) dont work; your must do the following, normally it will work
```
tns platform remove android
tns platform add android
```

**Comment by BlackCat1606** [comment]
@kefahB  , well it worked for me , but unless we got a response from the repo owner , we still don't have a clue about the solution , so please @triniwiz  be more active and answer this issue

**Comment by kefahB** [comment]
@BlackCat1606  if you see  [this PR](https://github.com/triniwiz/nativescript-socketio/commit/bdcdda7b6d20aca1eecbcded09b0c1a84e752dac#diff-4cfcbd540399d850125fdbc496e2c89a) the type of socket is any and it was modified...

It work now, you can continue working until we have the return of @triniwiz 
;-)

**Comment by jogboms** [comment]
@triniwiz 🤠

**Comment by luisalcarasr** [comment]
I have the same issue!

**Comment by abalad** [comment]
same here
```
node_modules/nativescript-socketio/socketio.android.d.ts(3,23): error TS2503: Cannot find namespace 'io'.
node_modules/nativescript-socketio/socketio.android.d.ts(3,23): error TS2503: Cannot find namespace 'io'.
node_modules/nativescript-socketio/socketio.android.d.ts(3,23): error TS2503: Cannot find namespace 'io'.
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
node_modules/nativescript-socketio/socketio.android.d.ts(3,23): error TS2503: Cannot find namespace 'io'.
node_modules/nativescript-socketio/socketio.android.d.ts(3,23): error TS2503: Cannot find namespace 'io'.
node_modules/nativescript-socketio/socketio.android.d.ts(3,23): error TS2503: Cannot find namespace 'io'.
node_modules/nativescript-socketio/socketio.android.d.ts(3,23): error TS2503: Cannot find namespace 'io'.
node_modules/nativescript-socketio/socketio.android.d.ts(3,23): error TS2503: Cannot find namespace 'io'.
node_modules/nativescript-socketio/socketio.android.d.ts(3,23): error TS2503: Cannot find namespace 'io'.
```

**Comment by mnkeis** [comment]
Same issue, @BlackCat1606 workaround worked for me.

**Comment by grendizeras** [comment]
Same issue here. It seems that it can't detect types that are in typings folder. Any solution?

**Comment by BlackCat1606** [comment]
@grendizeras  did you try the work around that i talked about earlier in this issue ?

**Comment by grendizeras** [comment]
@BlackCat1606  Yes I did, but it is temporary solution. Thanks BTW.

**Comment by triniwiz** [comment]
Hi everyone can you paste your tns android version thanks

**Comment by kefahB** [comment]
@triniwiz Thanks for your for reply 
```json
"tns-android": {
	"version": "4.1.3"
}
```

**Comment by grendizeras** [comment]
"tns-android": {
      "version": "4.1.3"
    }

"typescript": "~2.7.2",

**Comment by mnkeis** [comment]
Here
 "tns-android": {
      "version": "4.1.3"
    }

**Comment by triniwiz** [comment]
Looks like everyone is on v4 so all that’s needs to be done is update the include.gradle

**Comment by kefahB** [comment]
Hi,

Where include.gradle is located please ?

**Comment by kefahB** [comment]
I have no include.gradle file in `projet_name/platforms/android/`

**Comment by triniwiz** [comment]
@kefahB it’s in the `node_modules/pluginname`

**Comment by kefahB** [comment]
@triniwiz There is no include.gradle also ! can you explain for us what we must do in details please :-)

**Comment by mnkeis** [comment]
I've found an include.gradle in node_modules/nativescript-socketio/platforms/android but no clue how to update it.
Follow file content

// 

android {
	
}

dependencies {
	compile('io.socket:socket.io-client:0.8.2') {
		exclude group: 'org.json', module: 'json'
	}
}
