### ISSUE TITLE
IOS receiving json with parentheses !!!

### ISSUE THREAD

**Issue by kefahB** [triniwiz/nativescript-socketio#61]
### Did you verify this is a real problem by searching the [NativeScript Forum](http://forum.nativescript.org) and the [other open issues in this repo](https://github.com/NativeScript/nativescript/issues)?
YES
### Tell us about the problem
Please, ensure your title is less than 63 characters long and starts with a capital
letter.

I use socio.io Server and when i emit event from server i recive : 
```js
(
{
"auth_id" = 687019;
}
)
```
no problem with android i receive :
```js
{
"auth_id" = 687019;
}
```

### Which platform(s) does your issue occur on?
iOS
### Please provide the following version numbers that your issue occurs with:
- CLI: 4.1.0
- Cross-platform modules: "tns-core-modules": "^4.1.0",
- Runtime(s): 
"tns-android": {
			"version": "4.1.3"
		},
		"tns-ios": {
			"version": "4.1.1"
		}
- Plugin(s): (look for the version number in the `package.json` file of your
project)

```js
//server.js
const http = require("http");
const server = http.createServer();
const io = require("socket.io")(server);

io.on("connect", (socket) => {
socket.emit("auth_id", {auth_id: 123});
});

//IOS
socketIO.on("auth_id", (data) => {
        console.log("AUTHORISATION ID :");
        console.log(data);
        //output
(
{
"auth_id" = 123;
}
)
```

Thnk you :)

**Comment by kefahB** [comment]
@jogboms Have you idea about this ? @triniwiz is not active

**Comment by kefahB** [comment]
I add deserialize(), is not a solution but I need to continu to work until we have a real soulution
```js
// nodes-modules/nativescript-socketio/socketio.ios.d.js
SocketIO.prototype.on = function (event, callback) {
        this.socket.onCallback(event, function (data, ack) {
            data = deserialize(data); // HERE I RECEIVE [{msg: "HELLOE}] and I can use it
            if (ack) {
                callback(data[0], ack);
            }
            else {
                callback(data[0]);
            }
        });
    };
```

**Comment by jogboms** [comment]
Sorry @kefahB, i'm a bit swamped with office work lately.
