### ISSUE TITLE
IOS : WebSocket.swift "characters" is deprecated !

### ISSUE THREAD

**Issue by kefahB** [triniwiz/nativescript-socketio#62]
Hello,

I read this msg when the app compile : 

`
PROJECT_NAME/platforms/ios/Pods/StarscreamSocketIO/Source/WebSocket.swift:668:37: warning: 'characters' is deprecated: Please use String or Substring directly
                    if headerSecKey.characters.count > 0 {
`

There is no error momently, the websocket work, but maybe this error come from ?? [#61](https://github.com/triniwiz/nativescript-socketio/issues/61)  

Thank you

**Comment by b02505048** [comment]
Am having the same problem, any solution?

**Comment by kefahB** [comment]
Hi, if you have the last version of Websocket.io (2.5.0) and you have updatef for the latest take a look to your PodFile and chek if you ther is no double declaration of swift ?

**Comment by SergioZhydecky** [comment]
I have the same issue
