### ISSUE TITLE
Socket.io connectParams if pass undefined crash

### ISSUE THREAD

**Issue by sargin48** [triniwiz/nativescript-socketio#63]
```
SocketIOModule.forRoot('http://192.168.1.181:3011', {
    connectParams: { token: BackendService.token}
}),
```

i solve with
```
        SocketIOModule.forRoot('http://api.baskonus.abdullahsargin.com.tr', {
            connectParams: { token: (BackendService.token || '') }
        }),
```

if you pass token undefined you give 
please add param undefined control.
I spent at least 4 hours to find this error

I opened this error for documentation purposes.
you can turn it off at any time

*** JavaScript call stack:
(
0   initWithSocketURLConfig@[native code]
1   SocketIO@file:///app/tns_modules/nativescript-socketio/socketio.js:35:82
2   socketIOFactory@file:///app/tns_modules/nativescript-socketio/angular/index.js:8:35
3   _createProviderInstance$1@file:///app/tns_modules/@angular/core/bundles/core.umd.js:9321:38
4   resolveNgModuleDep@file:///app/tns_modules/@angular/core/bundles/core.umd.js:9284:46
5   createClass@file:///app/tns_modules/@angular/core/bundles/core.umd.js:10236:151
6   createDirectiveInstance@file:///app/tns_modules/@angular/core/bundles/core.umd.js:10117:31
7   createViewNodes@file:///app/tns_modules/@angular/core/bundles/core.umd.js:11339:59
8   createRootView@file:///app/tns_modules/@angular/core/bundles/core.umd.js:11253:20
9   callWithDebugContext@file:///app/tns_modules/@angular/core/bundles/core.umd.js:12288:30
10  create@file:///app/tns_modules/@angular/core/bundles/core.umd.js:9597:43
11  bootstrap@file:///app/tns_modules/@angular/core/bundles/core.umd.js:5119:46
12  forEa<\M-b\M^@\M-&>
)
*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** -[__NSPlaceholderDictionary initWithObjects:forKeys:count:]: attempt to insert nil object from objects[0]'

**Comment by triniwiz** [comment]
@sargin48 you can try v3 and let me know 😄
