### ISSUE TITLE
IOS - ANDROID - query params conflict

### ISSUE THREAD

**Issue by kefahB** [triniwiz/nativescript-socketio#66]
Hi @triniwiz 

I have found an issu about sending query params.

`android` :  accept passing params in url but it dose not accept passing in options side
`ios` :  accept passing params in options side but dose not accept in url url :-)

Like this it work.

```
let url = "http://127.0.0.1:3001?id=foo&user=bar"; // I try with remote url same result
socket = new SocketIO(url, {
            query: {
                 id: "foo",
                  user: "bar"
           }
});
```

Thanks

**Comment by triniwiz** [comment]
Ok i'll look into it 😄

**Comment by triniwiz** [comment]
Should be fixed now
