### ISSUE TITLE
False boolean value in payload is transformed to true

### ISSUE THREAD

**Issue by bilel-noomene** [triniwiz/nativescript-socketio#68]
Hello,
I'm trying to return an object with boolean values from the server. I find that «false» values are transformed to «true». I reproduced the problem on my fork ([here](https://github.com/bilel-noomene/nativescript-socketio/commit/5d1e10478b751aedb33a852f1f9a9e7222c8f0a1)).

PS: I tested only on Android.

**Comment by matanstorr** [comment]
+1, happens to me as well.

**Comment by triniwiz** [comment]
Only android ?

**Comment by bilel-noomene** [comment]
I haven't tested on ios yet.

**Comment by triniwiz** [comment]
@bilel-noomene @matanstorr It's fixed in the latest release
