### ISSUE TITLE
iOS build fails with Apps/MyApp/platforms/ios/Pods/Starscream/Sources/Starscream/WebSocket.swift:24:8: error: no such module 'CommonCrypto'

### ISSUE THREAD

**Issue by ggarabedian** [triniwiz/nativescript-socketio#72]
### Which platform(s) does your issue occur on?
- iOS / Xcode 9.x 

### Please, provide the following version numbers that your issue occurs with:
- CLI: 4.2.3
- Cross-platform modules: 4.2.0
- Runtime(s): 4.2.0
- Plugin(s): "nativescript-socketio": "3.2.1"

### Please, tell us how to recreate the issue in as much detail as possible. 
To reproduce the issue you just need to create a new app and add the nativescript-socketio plugin. Also, ensure that the pods on your system are updated to their latest version (`pod repo update` command).

The issue seems to be related to [version 3.0.6 of the Starscream library](https://github.com/daltoniam/Starscream/tree/3.0.6), which is a dependency of a dependency ([socket.io-client-swift](https://github.com/triniwiz/socket.io-client-swift)) of the nativescript-socketio plugin. There is an [issue](https://github.com/daltoniam/Starscream/issues/575) opened in the Starscream repository about the same problem. It looks like 3.0.6 introduces support for Xcode 10, which is already available, but it would be great to have a stable version of the nativescript-socketio plugin for Xcode 9.x users as well.

**Comment by nginx17** [comment]
@ggarabedian try add `pod 'Starscream', '<= 3.0.5'` in Podfile

**Comment by nginx17** [comment]
@triniwiz  if I use the starscream 3.0.5, the "common crypto" problem is solved but I find a new problem that can't be solved yet:
`error: cannot use instance member {'socket' & 'nsp',} run before 'self' property initializers is available`

This error is sourced from SocketIOclient.swift
