### ISSUE TITLE
Angular 10 update

### ISSUE THREAD

**Issue by rsboarder** [triniwiz/nativescript-socketio#99]
Bug with Angular 10
```
SocketIOModule.forRoot returns a ModuleWithProviders type without a generic type argument. Please add a generic type argument to the ModuleWithProviders type. If this occurrence is in library code you don't control, please contact the library authors.
```

### Which platform(s) does your issue occur on?
Both

### Please, tell us how to recreate the issue in as much detail as possible. 
Simply start app

**Comment by triniwiz** [comment]
Wip it will be published soon

**Comment by nuno-morais** [comment]
Hello,
@triniwiz when will you publish a new version?

**Comment by triniwiz** [comment]
@nuno-morais https://github.com/triniwiz/nativescript-plugins [new docs](https://triniwiz.github.io/nativescript-plugins/api-reference/socketio.html)

**Comment by nuno-morais** [comment]
Thanks. Maybe this issue should be closed :)

**Comment by nuno-morais** [comment]
BTW, I've found an issue here: https://github.com/triniwiz/nativescript-plugins/blob/master/packages/nativescript-socketio/platforms/android/include.gradle

You didn't close the brackets. 🤔

**Comment by triniwiz** [comment]
should be all fixed up now :) release `4.0.1`

**Comment by EricBorland** [comment]
Hi @triniwiz , when would that be released? Last release appears to be still 3.x

**Comment by triniwiz** [comment]
@EricBorland `@triniwiz/nativescript-socketio`
